### PR TITLE
Fixes for #2 composer and #3 jumpurl

### PR DESCRIPTION
**Pull request by villamarianne**
Fixes https://github.com/jokumer/direct_mail/issues/2 and https://github.com/jokumer/direct_mail/issues/3

### CODE REVIEW

**Review by jokumer — COMMENTED** [review]
The change "[BUGFIX] Update composer dependencies" is already requested by Patrick Lenk Patta "[!!!][TASK] Bump tt_address from ^4.3 to ^5.0"
Which I am not sure about. It should be possible, to use both tt_addres v4.x and v5.x

**Comment by villamarianne** [comment]
I guess you are right, sorry for the duplicate PR.

**Comment by jokumer** [comment]
No problem, I fix it. Later

**Comment by Patta** [comment]
> The change "[BUGFIX] Update composer dependencies" is already requested by Patrick Lenk Patta "[!!!][TASK] Bump tt_address from ^4.3 to ^5.0"
> Which I am not sure about. It should be possible, to use both tt_addres v4.x and v5.x

@jokumer, TYPO3 8 LTS is only official supported until 31.03.2020. Therefore the tt_address v4.x dependency which supports TYPO3 8.7 could be dropped in a new direct_mail release which do (should) not support TYPO3 8 LTS anymore.

**Comment by jokumer** [comment]
But tt_address v4.0-v4.3 is TYPO3 v9.5 compatible and those some one may still have dependencies on older versions of tt_address. Therefor direct_mail should be compatible with tt_address 4.3 at least.

**Comment by Patta** [comment]
Seems legit, but then the tt_address constraint must be at least `^4.3 || ^5.0`. Otherwise direct_mail can't be installed on distributions with a site_package that requires tt_address `^5.0`.

**Pull request merged**
